### PR TITLE
fix totem bar dismissal

### PR DESCRIPTION
**Pull request by Fktor**
Fixes not being able to dismiss totems via right-clicking. Now, I'm not a wow modder - please check if it's the correct way to do it!

### CODE REVIEW

**Comment by parnic** [comment]
Have you tried this during combat?

**Review by parnic — CHANGES_REQUESTED** [review]
This is what happens when right-clicking a totem with this change:

image

**Comment by Fktor** [comment]
Hmm... trying to replicate this, but it works fine for me, combat or not :/ TBC 2.5.2 (40892).

**Comment by parnic** [comment]
Ah - I don't think secure execution was a thing in the TBC era. In that case, guard these changes with checks for WoW version so it doesn't try to run on retail (Shadowlands/9.x). Check IceHUD.lua or other code files for examples of how to do this.

**Comment by Fktor** [comment]
Fixed - works on TBC classic and retail. Have no level 4 shaman to try it on classic, but should as well.

I also looked at how to make it work on retail, but I assume that would require inheriting the button from SecureActionButtonTemplate, which would be a huge change.

**Review by parnic — APPROVED** [review]

**Comment by parnic** [comment]
Thanks. Yes, I've tried making it inherit from a secure frame, but it still causes problems.

**Pull request merged**
